### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Jakousa** [ohnoize/fullstack-project#14]
# Full Stack projektin katselmointi

Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit halutessasi ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

### Mitä tein? ###

Käytin hetken rekisteröimättä

Rekisteröidyin

Kirjauduin sisään

Käytin sovellusta hetken

Tallensin session

Tein tavoitteen

Käytin sovellusta

### Kokemus ###

Siistit sivut!

Selkeähkö käyttää, osaa toiminnoista voisi hieoa vähän intuitiivisemmaksi.

Tavoitelista etusivulla on tyhjä vaikka minulla pitäisi olla tavoite. Jos aloitan harjoittelun niin tavoitteesta kuitenkin vähenee aika.. Ehkä koska deadline on tänään niin ei kaikki logiikka toimi ihan oikein?

## Koodi ##

Committien kanssa sulla tapahtuu jotain outoa. Tai sitten kaksi eri Olli Hirvosta ollut tekemässä projektia.

Projektin rakenne on selkeä, on helppo löytää tiedostot ja ne on jaettu pääosin järkeviin kokonaisuuksiin.

Tässä komponentissa on aika mielenkiintoinen logiikka returnin sisällä. Pystyisiköhän sitä jotenkin yksinkertaistamaan, esim jakaa useampaan komponenttiin? https://github.com/ohnoize/fullstack-project/blob/main/src/components/MySubjects.jsx

Onkohan kahteen eri repositorioon jakaminen oleellista projektille? Kuvittelen että niiden yhdistäminen kävisi enemmän järkeen kuin erilleen jakaminen.

## Kokonaisuus ##

Hieno projekti ja todella hyvä idea! Tämähän on lähes julkaisukelpoinen, milloin näen reddit postauksen ja rupeat keräämään käyttäjiä?

**Comment by ohnoize** [comment]
Kiitos paljon palautteesta! Muutamat bugit olivatkin jo tiedossa, ja muutenkin pelkästään hyviä huomioita jotka menevät korjaukseen asap. 

Selvennykseksi halusin kysyä tuosta projektin repositorioihin jaosta. Ehdotat siis että olisi selkeämpi pistää front- ja backendit samaan repositorioon (vaikka "server" ja "web" kansioihin) ja myös hostaisin ne samassa paikassa? Tällä tavalla backend voisi myös "servata" suoraan frontin sisällön ilman tarvetta hostata sitä ulkopuolisessa palvelussa, eikö näin? Päätin pitää API:n koodin erillään jotta se voisi palvella myös mahdollista tulevaa mobiiliapplikaatiota, mutta käytännössähän tämä ei tietenkään vaadi omaa repoa, kunhan endpointit on kunnossa. Pistetään siis harkintaan.

Mutta kiitos kehuista ja huomioista! Tavoitteena on tosiaan saada tämä julkiseksi, kunhan saan bugit ja muutamat kirjautumiseen/tokeneiden säilyttämiseen liityvät turvallisuusissuet selviteltyä.

**Comment by Jakousa** [comment]
Joo monorepot on yleistynyt ja vaikka itsekin tykkäsin pitää "eri koodit eri repoissa" niin olen vaihtanut tähän "Pidä yksi kokonaisuus omassa repossa" idealla. Kaikki ci putket ja sensellaiset saa yleensä kunnioittamaan samassa repositoriossa toimimista. Sinulla voi sitten olla vaikkapa "cool-application" repositorio jossa "api-backend", "mobile-app", "web-app" projektit.

Eräs kova legendaarinen monorepo on Google, jolla on koko hoito yhdessä repositoriossa. Täältä lisää asiasta https://trunkbaseddevelopment.com/monorepos/

Oikeasti monorepo on kuitenkin mielipideasia, eli voit tykätä ja käyttää kumpaa vain.

**Comment by ohnoize** [comment]
Jes, kiitos vinkeistä.
